# https://docs.helix-editor.com/editor.html

theme = "tokyonight"

[editor]
line-number = "relative"
cursorline = true
idle-timeout = 5
completion-timeout = 5

[editor.cursor-shape]
insert = "bar"

[editor.indent-guides]
render = true
character = "▏"
skip-levels = 1


# https://docs.helix-editor.com/keymap.html
# https://github.com/LGUG2Z/helix-vim/blob/master/config.toml

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
C-s = ":write"
C-left = ["move_prev_word_start", "collapse_selection"]
C-h = ["move_prev_word_start", "collapse_selection"]
C-right = ["move_next_word_end", "move_char_right", "collapse_selection"]
C-l = ["move_next_word_end", "move_char_right", "collapse_selection"]
A-up = [
  "collapse_selection",
  "extend_line_below",
  "delete_selection",
  "move_line_up",
  "paste_before",
]
A-down = [
  "collapse_selection",
  "extend_line_below",
  "delete_selection",
  "move_line_down",
  "paste_before",
]

[keys.insert]
esc = ["collapse_selection", "normal_mode"]
C-s = [":write", "normal_mode"]
C-ret = ["normal_mode", "open_below", "insert_mode"]
C-left = [
  "normal_mode",
  "move_prev_word_start",
  "collapse_selection",
  "insert_mode",
]
C-right = [
  "normal_mode",
  "move_next_word_end",
  "move_char_right",
  "collapse_selection",
  "insert_mode",
]

[keys.select]
esc = ["collapse_selection", "keep_primary_selection", "normal_mode"]
