[language-server.scls]
command = "simple-completion-language-server"

[language-server.scls.config]
max_completion_items = 100           # set max completion results len for each group: words, snippets, unicode-input
feature_words = true                 # enable completion by word
feature_snippets = true              # enable snippets
snippets_first = true                # completions will return before snippets by default
snippets_inline_by_word_tail = false # suggest snippets by WORD tail, for example text `xsq|` become `x^2|` when snippet `sq` has body `^2`
feature_unicode_input = false        # enable "unicode input"
feature_paths = false                # enable path completion
feature_citations = false            # enable citation completion (only on `citation` feature enabled)

[[language]]
name = "toml"
formatter = { command = "taplo", args = ["fmt", "-"] }
auto-format = true
roots = ["."]                                          # fixes language server for now

[[language]]
name = "html"
language-servers = ["vscode-html-language-server", "tailwindcss-ls", "scls"]

[[language]]
name = "vento"
language-servers = ["vscode-html-language-server", "tailwindcss-ls", "scls"]
formatter = { command = 'prettier', args = ["--parser", "html"] }
auto-format = true

[[language]]
name = "css"
language-servers = ["vscode-css-language-server", "tailwindcss-ls", "scls"]

[[language]]
name = "jsx"
language-servers = ["typescript-language-server", "tailwindcss-ls", "scls"]
formatter = { command = 'prettier', args = ["--parser", "typescript"] }
auto-format = true

[[language]]
name = "tsx"
language-servers = ["typescript-language-server", "tailwindcss-ls", "scls"]
formatter = { command = 'prettier', args = ["--parser", "typescript"] }
auto-format = true

[[language]]
name = "javascript"
formatter = { command = 'prettier', args = ["--parser", "typescript"] }
auto-format = true

[[language]]
name = "typescript"
formatter = { command = 'prettier', args = ["--parser", "typescript"] }
auto-format = true

[[language]]
name = "markdown"
formatter = { command = 'prettier', args = ["--parser", "markdown"] }
auto-format = true

[[language]]
name = "bash"
formatter = { command = 'shfmt' }
auto-format = true

[language-server.astro-ls]
command = "astro-ls"
args = ["--stdio"]
config = { typescript = { tsdk = "/opt/node_modules/typescript/lib" }, environment = "node" }

[[language]]
name = "astro"
language-servers = ["astro-ls", "tailwindcss-ls", "scls"]
formatter = { command = 'prettier', args = [
  "--plugin",
  "/opt/node_modules/prettier-plugin-astro/dist/index.js",
  "--parser",
  "astro",
] }
auto-format = true

[[language]]
name = "go"
auto-format = true
formatter = { command = "goimports" }

# Note: VueLS shits the bed after two or three saves
[[language]]
name = "vue"
auto-format = true
formatter = { command = "prettier", args = ["--parser", "vue"] }
language-servers = ["typescript-language-server", "tailwindcss-ls", "scls"]

[[language-server.typescript-language-server.config.plugins]]
name = "@vue/typescript-plugin"
location = "/opt/node_modules/@vue/language-server/"
languages = ["vue"]

[[language]]
name = "typescript"
language-id = "typescript"
scope = "source.ts"
injection-regex = "^(ts|typescript)$"
file-types = ["ts", "tsx", "js", "jsx"]
shebangs = ["deno"]
roots = ["deno.json", "deno.jsonc", "package.json"]
auto-format = true
language-servers = ["deno-lsp", "tailwindcss-ls", "scls"]

[language-server.deno-lsp]
command = "deno"
args = ["lsp"]

[language-server.deno-lsp.config.deno]
enable = true

[[language]]
name = "svelte"
auto-format = true
formatter = { command = 'prettier', args = [
  "--plugin",
  "/opt/node_modules/prettier-plugin-svelte/plugin.js",
  "--parser",
  "svelte",
] }
