[[snippets]]
prefix = "ll"
scope = ["typescript"]
body = 'console.log($1)'
description = "console.log()"

[[snippets]]
prefix = "comp"
scope = ["tsx"]
description = "Solid Component"
body = """import { type Component, mergeProps } from "solid-js";
import list from "clsx";

interface Props {
  name: string;
}

const C: Component<Props> = (p) => {
  const props = mergeProps({ name: "" }, p);

  return (
    <div class={list(["flex"])}>
      $1
    </div>
  )
}

export default C
"""
